In [6]:
import pandas as pd
import numpy as np

In [88]:
def get_half_hour_value(list_quarter_mins):
    sum_kWHr=0
    list_half_hour=[]
    for ind, i in enumerate(list_quarter_mins):
        if ind % 2 ==1:
            sum_kWHr=sum_kWHr+i
            list_half_hour.append(sum_kWHr)
            sum_kWHr=0
        else:
            sum_kWHr=sum_kWHr+i


    return list_half_hour

In [89]:
get_half_hour_value([-10,20,30,40,100,120])

[10, 70, 220]

In [16]:
# df_AMR=pd.read_excel("AMR_DATA_COMBINE_SUB.xlsx")

In [109]:
df_AMR=pd.read_csv("AMR_DATA_COMBINE_SUB.csv")

In [111]:
df_AMR['AMR_OUT01']

0      [{21652: array([[1.51603212e-02, 1.47840012e-0...
1      [{21652: array([[0.02771328, 0.02763264, 0.027...
2      [{21652: array([[3.25868954, 0.02327808, 3.860...
3      [{21652: array([[2.65730325e+00, 2.93529623e-0...
4      [{21652: array([[2.90414231e+00, 2.13158417e-0...
5      [{21652: array([[3.86655390e+00, 1.21629322e+0...
6      [{21652: array([[3.15307801e+00, 2.12352017e-0...
7      [{21652: array([[3.85652766e+00, 1.57640460e+0...
8      [{21652: array([[1.62161677, 3.87994015, 0.024...
9      [{21652: array([[3.86964510e+00, 2.45995027e+0...
10     [{21652: array([[3.84722718e+00, 1.68537613e-0...
11     [{21652: array([[2.92992023e-02, 7.21513017e-0...
12     [{21652: array([[2.36780563e+00, 3.81760542e+0...
13     [{21652: array([[3.87851551e+00, 1.38023435e+0...
14     [{21652: array([[3.86623134e+00, 3.86999454e+0...
15     [{21652: array([[3.86588190e+00, 1.58600076e+0...
16     [{21652: array([[2.77909654e+00, 2.21760017e-0...
17     [{21652: array([[2.84928

In [18]:
#Train set = 2018
#drop 2019
temp_df=df_AMR.drop(list(np.where(df_AMR['Year']!=2018)[0])).copy()
temp_df=temp_df.reset_index(drop=True)


temp_dict={'AMR_0001': ([])}



a=np.array([[],[],[],[],[],[],[],[],
            [],[],[],[],[],[],[],[],
            [],[],[],[],[],[],[],[],
            [],[],[],[],[],[],[],[],
            [],[],[],[],[],[],[],[],
            [],[],[],[],[],[],[],[]])

In [100]:
temp_df['AMR_OUT01'][0]

'[{21652: array([[1.51603212e-02, 1.47840012e-02, 1.47033612e-02, 1.47571212e-02,\n        1.48377612e-02, 1.47033612e-02, 1.47840012e-02, 1.47571212e-02,\n        1.47302412e-02, 1.47033612e-02, 1.45958411e-02, 1.51603212e-02,\n        1.46227212e-02, 1.45958411e-02, 1.45152011e-02, 1.45689611e-02,\n        1.45958411e-02, 1.45689611e-02, 1.44614411e-02, 1.45958411e-02,\n        1.46227212e-02, 1.82784014e-03, 1.51065612e-02, 0.00000000e+00,\n        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.67712037e-03,\n        8.14464064e-03, 8.03712063e-03, 2.10096785e+00, 3.84330270e+00,\n        3.83040030e+00, 1.49990412e-02, 3.78674718e+00, 3.78943518e+00,\n        3.75494814e+00, 3.74978718e+00, 1.46189580e+00, 0.00000000e+00,\n        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,\n        1.49990412e-02, 0.00000000e+00, 2.68800021e-05, 0.00000000e+00,\n        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,\n        2.68800021e-05, 0.00000000e+00, 0

In [49]:
empty_list=[]
a=np.array([] for _ in range(5))
print(a)

<generator object <genexpr> at 0x000000000617FC00>


In [76]:
a=np.array([[],[],[],[],[],[],[],[],
            [],[],[],[],[],[],[],[],
            [],[],[],[],[],[],[],[],
            [],[],[],[],[],[],[],[],
            [],[],[],[],[],[],[],[],
            [],[],[],[],[],[],[],[]])
a=np.append(a, [[1],[2],[3],[4],[5],[6],[7],[8],
            [9],[10],[11],[12],[13],[14],[15],[16],
            [17],[18],[19],[20],[21],[22],[23],[24],
            [25],[26],[27],[28],[29],[30],[31],[32],
            [33],[34],[35],[36],[37],[38],[39],[40],
            [41],[42],[43],[44],[45],[46],[47],[48]], axis=1)
a=np.append(a, [[1],[2],[3],[4],[5],[6],[7],[8],
            [9],[10],[11],[12],[13],[14],[15],[16],
            [17],[18],[19],[20],[21],[22],[23],[24],
            [25],[26],[27],[28],[29],[30],[31],[32],
            [33],[34],[35],[36],[37],[38],[39],[40],
            [41],[42],[43],[44],[45],[46],[47],[48]], axis=1)
print(a)

[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]
 [ 4.  4.]
 [ 5.  5.]
 [ 6.  6.]
 [ 7.  7.]
 [ 8.  8.]
 [ 9.  9.]
 [10. 10.]
 [11. 11.]
 [12. 12.]
 [13. 13.]
 [14. 14.]
 [15. 15.]
 [16. 16.]
 [17. 17.]
 [18. 18.]
 [19. 19.]
 [20. 20.]
 [21. 21.]
 [22. 22.]
 [23. 23.]
 [24. 24.]
 [25. 25.]
 [26. 26.]
 [27. 27.]
 [28. 28.]
 [29. 29.]
 [30. 30.]
 [31. 31.]
 [32. 32.]
 [33. 33.]
 [34. 34.]
 [35. 35.]
 [36. 36.]
 [37. 37.]
 [38. 38.]
 [39. 39.]
 [40. 40.]
 [41. 41.]
 [42. 42.]
 [43. 43.]
 [44. 44.]
 [45. 45.]
 [46. 46.]
 [47. 47.]
 [48. 48.]]


In [112]:
a=np.array([[],[]])
print(a)

a=np.append(a, [[1],[2]], axis=1)
a=np.append(a, [[5],[6]], axis=1)
a=np.append(a, [[10],[11]], axis=1)

print(a)

[]
[[ 1.  5. 10.]
 [ 2.  6. 11.]]


In [ ]:
#dict_AMR_CI={'AMR_no_001':{'weekday':{'mean':[....48], 'lower':[....48], 'upper':[....48]}, 'holiday':{}}, 'AMR_no_002':{}}