In [3]:
RANDOM_STATE = 31415


In [14]:
from scipy.stats import uniform
import numpy as np
import pandas as pd
import seaborn
dataset = seaborn.load_dataset('titanic')
import scipy
import scipy.stats
import matplotlib
import matplotlib.pyplot as plt

In [4]:
uniform_dist = uniform(loc = 0, scale = 20)
uniform_dist.rvs(size = 10, random_state = RANDOM_STATE)


array([12.91637212, 13.5034834 , 19.41407972, 17.69608729, 18.18131685,
       16.47185933,  9.73419442, 12.41987159, 12.87024926,  8.00739132])

In [12]:
uniform_dist

In [8]:
dist_array=np.array([20,20])

In [9]:
dist_array.rvs(size = 10, random_state = RANDOM_STATE)

AttributeError: 'numpy.ndarray' object has no attribute 'rvs'

# disContinus random variable

## generate scipy.stats._distn_infrastructure.rv_sample model

In [69]:
from scipy.stats import rv_discrete
pclass_probability = pd.DataFrame({'probability': dataset.groupby(by = "pclass", as_index=False).size() / dataset.pclass.count()}).reset_index()


pclass_probability
values = pclass_probability.pclass
probabilities = pclass_probability.probability
custom_discrete_dist = rv_discrete(values=(values, probabilities))

# print(custom_discrete_dist)

custom_discrete_dist.rvs(size = 20)

array([3, 1, 1, 3, 3, 2, 3, 3, 2, 3, 2, 3, 3, 2, 1, 1, 2, 2, 2, 2])

# generate contineus random variable

In [70]:
# more link : https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.rvs.html
# https://stackoverflow.com/questions/22447797/how-do-you-use-scipy-stats-rv-continuous

In [71]:
# example with existing distribution    

In [93]:
import pandas as pd
import numpy as np

#generate a dataframe with random number for age from 0 - 9
df_age = pd.DataFrame(np.random.randint(low=0, high=9, size=(100, 1)),columns = ['age'])
#set up bins
bin = [x for x in np.arange(0,20,1)]

#use pd.cut function can attribute the values into its specific bins
category = pd.cut(df_age.age,bin)
category = category.to_frame()
category.columns = ['range']
#concatenate age and its bin
df_new = pd.concat([df_age,category],axis = 1)




In [96]:
category

range
0   (4.0, 5.0]
1   (5.0, 6.0]
2   (6.0, 7.0]
3   (0.0, 1.0]
4   (5.0, 6.0]
5   (2.0, 3.0]
6   (7.0, 8.0]
7          NaN
8   (4.0, 5.0]
9   (3.0, 4.0]
10  (0.0, 1.0]
11  (6.0, 7.0]
12  (6.0, 7.0]
13  (1.0, 2.0]
14  (1.0, 2.0]
15  (7.0, 8.0]
16  (4.0, 5.0]
17  (3.0, 4.0]
18         NaN
19  (5.0, 6.0]
20  (3.0, 4.0]
21  (2.0, 3.0]
22  (7.0, 8.0]
23  (7.0, 8.0]
24  (3.0, 4.0]
25  (7.0, 8.0]
26  (7.0, 8.0]
27  (1.0, 2.0]
28  (3.0, 4.0]
29  (1.0, 2.0]
..         ...
70  (2.0, 3.0]
71         NaN
72  (3.0, 4.0]
73  (1.0, 2.0]
74  (2.0, 3.0]
75  (6.0, 7.0]
76  (3.0, 4.0]
77  (5.0, 6.0]
78  (5.0, 6.0]
79  (3.0, 4.0]
80  (1.0, 2.0]
81  (4.0, 5.0]
82  (0.0, 1.0]
83  (0.0, 1.0]
84  (1.0, 2.0]
85  (3.0, 4.0]
86  (2.0, 3.0]
87  (5.0, 6.0]
88  (1.0, 2.0]
89  (7.0, 8.0]
90  (2.0, 3.0]
91  (5.0, 6.0]
92  (5.0, 6.0]
93  (3.0, 4.0]
94         NaN
95  (4.0, 5.0]
96  (6.0, 7.0]
97  (7.0, 8.0]
98  (4.0, 5.0]
99  (7.0, 8.0]

[100 rows x 1 columns]

In [94]:
age_probability = pd.DataFrame({'probability': df_age.groupby(by = "age", as_index=False).size() / df_age.age.count()}).reset_index()


In [95]:
age_probability

age  probability
0    0         0.07
1    1         0.09
2    2         0.14
3    3         0.09
4    4         0.20
5    5         0.08
6    6         0.15
7    7         0.09
8    8         0.09

In [80]:
sum(age_probability.probability)

1.0

In [98]:
values = age_probability.age
probabilities = age_probability.probability
custom_discrete_dist = rv_discrete(values=(values, probabilities))


In [102]:
custom_discrete_dist.rvs(size = 5000)

array([7, 4, 7, ..., 7, 6, 4])

In [103]:
custom_discrete_dist